<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orderItems = [
            [
                'item_id'          => 1,
                'order_id'         => 1,
                'product_id'       => 12,
                'product_name'     => 'MMT 340GSM',
                'quantity'         => 1.00,
                'price'            => 13200000.00,
                'calculated_price' => 13200000.00,
                'subtotal'         => 13200000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 340GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Baliho Gadai Mas Simpang Limun"}',
                'created_at'       => '2026-01-09 03:00:00',
                'updated_at'       => '2026-01-09 03:00:00',
            ],
            [
                'item_id'          => 2,
                'order_id'         => 2,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 120000.00,
                'calculated_price' => 120000.00,
                'subtotal'         => 120000.00,
                'specifications'   => '{"length":1.5,"width":3,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1,5x3 1x1 PERINGATAN ISRAK MIKRAJ"}',
                'created_at'       => '2026-01-09 04:30:00',
                'updated_at'       => '2026-01-09 04:30:00',
            ],
            [
                'item_id'          => 3,
                'order_id'         => 3,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 118750.00,
                'calculated_price' => 118750.00,
                'subtotal'         => 118750.00,
                'specifications'   => '{"length":1.25,"width":1.2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1m25x 1m20 SPANDUK JADWAL KHOTIB"}',
                'created_at'       => '2026-01-09 06:15:00',
                'updated_at'       => '2026-01-09 06:15:00',
            ],
            [
                'item_id'          => 4,
                'order_id'         => 4,
                'product_id'       => 17,
                'product_name'     => 'STICKER INDOOR',
                'quantity'         => 1.00,
                'price'            => 150000.00,
                'calculated_price' => 150000.00,
                'subtotal'         => 150000.00,
                'specifications'   => '{"length":17,"width":20,"material":"STICKER INDOOR","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Stiker Print And Cut 17X20 lip 6x6 Spray 20x20 Bedak"}',
                'created_at'       => '2026-01-12 02:00:00',
                'updated_at'       => '2026-01-12 02:00:00',
            ],
            [
                'item_id'          => 5,
                'order_id'         => 5,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 380000.00,
                'calculated_price' => 380000.00,
                'subtotal'         => 380000.00,
                'specifications'   => '{"length":5,"width":10,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Bilboard titikuning Brodkest 5x10 6x4"}',
                'created_at'       => '2026-01-12 07:00:00',
                'updated_at'       => '2026-01-12 07:00:00',
            ],
            [
                'item_id'          => 6,
                'order_id'         => 6,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 900000.00,
                'calculated_price' => 900000.00,
                'subtotal'         => 900000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk djarum brand D (15PCS)"}',
                'created_at'       => '2026-01-21 03:20:00',
                'updated_at'       => '2026-01-21 03:20:00',
            ],
            [
                'item_id'          => 7,
                'order_id'         => 7,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 5000000.00,
                'calculated_price' => 5000000.00,
                'subtotal'         => 5000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth Makeover Mastershade Meja Sun Plaza"}',
                'created_at'       => '2026-02-02 04:00:00',
                'updated_at'       => '2026-02-02 04:00:00',
            ],
            [
                'item_id'          => 8,
                'order_id'         => 8,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 412100.00,
                'calculated_price' => 412100.00,
                'subtotal'         => 412100.00,
                'specifications'   => '{"length":1,"width":3,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk Ikmas Milad uk.1x3, 3x2, 3x150, 1x4 dll"}',
                'created_at'       => '2026-02-10 02:30:00',
                'updated_at'       => '2026-02-10 02:30:00',
            ],
            [
                'item_id'          => 9,
                'order_id'         => 9,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 8000000.00,
                'calculated_price' => 8000000.00,
                'subtotal'         => 8000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth Emina Irian Marelan"}',
                'created_at'       => '2026-02-18 03:45:00',
                'updated_at'       => '2026-02-18 03:45:00',
            ],
            [
                'item_id'          => 10,
                'order_id'         => 10,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 15000000.00,
                'calculated_price' => 15000000.00,
                'subtotal'         => 15000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Photo Box Bpk Frans"}',
                'created_at'       => '2026-02-23 08:00:00',
                'updated_at'       => '2026-02-23 08:00:00',
            ],
            [
                'item_id'          => 11,
                'order_id'         => 11,
                'product_id'       => 17,
                'product_name'     => 'STICKER INDOOR',
                'quantity'         => 1.00,
                'price'            => 2415000.00,
                'calculated_price' => 2415000.00,
                'subtotal'         => 2415000.00,
                'specifications'   => '{"length":1,"width":1,"material":"STICKER INDOOR","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"revisual stiker pnt djarum 76 mangga royal 23 pcs"}',
                'created_at'       => '2026-03-31 02:10:00',
                'updated_at'       => '2026-03-31 02:10:00',
            ],
            [
                'item_id'          => 12,
                'order_id'         => 12,
                'product_id'       => 17,
                'product_name'     => 'STICKER INDOOR',
                'quantity'         => 1.00,
                'price'            => 1680000.00,
                'calculated_price' => 1680000.00,
                'subtotal'         => 1680000.00,
                'specifications'   => '{"length":1,"width":1,"material":"STICKER INDOOR","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"revisual stiker pnt djarum insta watermelon 16 pcs"}',
                'created_at'       => '2026-03-31 03:15:00',
                'updated_at'       => '2026-03-31 03:15:00',
            ],
            [
                'item_id'          => 13,
                'order_id'         => 13,
                'product_id'       => 14,
                'product_name'     => 'BACKLITE',
                'quantity'         => 1.00,
                'price'            => 600000.00,
                'calculated_price' => 600000.00,
                'subtotal'         => 600000.00,
                'specifications'   => '{"length":1,"width":1,"material":"BACKLITE","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Revisual Neon Box Djarum LA BOLD 5pcs"}',
                'created_at'       => '2026-03-31 04:30:00',
                'updated_at'       => '2026-03-31 04:30:00',
            ],
            [
                'item_id'          => 14,
                'order_id'         => 14,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi vbanner djarum Semi Permanen 20 unit ZONA LUBUK PAKAM 1"}',
                'created_at'       => '2026-05-05 06:00:00',
                'updated_at'       => '2026-05-05 06:00:00',
            ],
            [
                'item_id'          => 15,
                'order_id'         => 15,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi vbanner djarum Semi Permanen 20 unit ZONA LUBUK PAKAM 2"}',
                'created_at'       => '2026-05-05 06:10:00',
                'updated_at'       => '2026-05-05 06:10:00',
            ],
            [
                'item_id'          => 16,
                'order_id'         => 16,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi vbanner djarum Semi Permanen 20 unit ZONA PERBAUNGAN"}',
                'created_at'       => '2026-05-05 06:20:00',
                'updated_at'       => '2026-05-05 06:20:00',
            ],
            [
                'item_id'          => 17,
                'order_id'         => 17,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi vbanner djarum Semi Permanen 20 unit ZONA SEI RAMPAH"}',
                'created_at'       => '2026-05-05 06:30:00',
                'updated_at'       => '2026-05-05 06:30:00',
            ],
            [
                'item_id'          => 18,
                'order_id'         => 18,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 500000.00,
                'calculated_price' => 500000.00,
                'subtotal'         => 500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Pemasangan vb apel royal 5 unit (malam-malam)"}',
                'created_at'       => '2026-05-06 03:00:00',
                'updated_at'       => '2026-05-06 03:00:00',
            ],
            [
                'item_id'          => 19,
                'order_id'         => 19,
                'product_id'       => 1,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3774720.00,
                'calculated_price' => 3774720.00,
                'subtotal'         => 3774720.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Rebranding PNT Toko Serasi dan Toko Jona Indofood"}',
                'created_at'       => '2026-05-07 02:00:00',
                'updated_at'       => '2026-05-07 02:00:00',
            ],
            [
                'item_id'          => 20,
                'order_id'         => 20,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 70000.00,
                'calculated_price' => 70000.00,
                'subtotal'         => 70000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk uk 4mx75cm (1pcs) Qurban mesjid"}',
                'created_at'       => '2026-05-07 04:30:00',
                'updated_at'       => '2026-05-07 04:30:00',
            ],
            [
                'item_id'          => 21,
                'order_id'         => 21,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 850000.00,
                'calculated_price' => 850000.00,
                'subtotal'         => 850000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Maintenance Backwall Wardah Berastagi Cemara"}',
                'created_at'       => '2026-05-08 07:00:00',
                'updated_at'       => '2026-05-08 07:00:00',
            ],
            [
                'item_id'          => 22,
                'order_id'         => 22,
                'product_id'       => 1,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 23454750.00,
                'calculated_price' => 23454750.00,
                'subtotal'         => 23454750.00,
                'specifications'   => '{"length":7,"width":1.2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi PNT AGAM NYAK WELL Indofood uk. 7x1,2 m"}',
                'created_at'       => '2026-05-11 03:15:00',
                'updated_at'       => '2026-05-11 03:15:00',
            ],
            [
                'item_id'          => 23,
                'order_id'         => 23,
                'product_id'       => 5,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Akrilik Nama PT.WAHANATAMA HIJAU MUTIARA MANDIRI"}',
                'created_at'       => '2026-05-19 02:30:00',
                'updated_at'       => '2026-05-19 02:30:00',
            ],
            [
                'item_id'          => 24,
                'order_id'         => 24,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 500000.00,
                'calculated_price' => 500000.00,
                'subtotal'         => 500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Maintenance Sis Wardah dan OMG Perfect 10"}',
                'created_at'       => '2026-05-13 06:45:00',
                'updated_at'       => '2026-05-13 06:45:00',
            ],
            [
                'item_id'          => 25,
                'order_id'         => 25,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 350000.00,
                'calculated_price' => 350000.00,
                'subtotal'         => 350000.00,
                'specifications'   => '{"length":5,"width":280,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK.5x280:1pc welcome to Paragon day"}',
                'created_at'       => '2026-05-13 08:00:00',
                'updated_at'       => '2026-05-13 08:00:00',
            ],
            [
                'item_id'          => 26,
                'order_id'         => 26,
                'product_id'       => 5,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 4000000.00,
                'calculated_price' => 4000000.00,
                'subtotal'         => 4000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Logo Suit En Flor"}',
                'created_at'       => '2026-05-19 04:20:00',
                'updated_at'       => '2026-05-19 04:20:00',
            ],
            [
                'item_id'          => 27,
                'order_id'         => 27,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 500000.00,
                'calculated_price' => 500000.00,
                'subtotal'         => 500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Maintenance Backwall Wardah Skincare Underprice Jamin Ginting"}',
                'created_at'       => '2026-05-10 02:00:00',
                'updated_at'       => '2026-05-10 02:00:00',
            ],
            [
                'item_id'          => 28,
                'order_id'         => 28,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 35000.00,
                'calculated_price' => 35000.00,
                'subtotal'         => 35000.00,
                'specifications'   => '{"length":1,"width":3,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK 1x3: 1lbr Pelantikan ASSI Sumut"}',
                'created_at'       => '2026-05-20 03:30:00',
                'updated_at'       => '2026-05-20 03:30:00',
            ],
            [
                'item_id'          => 29,
                'order_id'         => 29,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 22400.00,
                'calculated_price' => 22400.00,
                'subtotal'         => 22400.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK 80x,2:1pc Rekreasi Karyawan Advertising"}',
                'created_at'       => '2026-05-20 07:00:00',
                'updated_at'       => '2026-05-20 07:00:00',
            ],
            [
                'item_id'          => 30,
                'order_id'         => 30,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 230000.00,
                'calculated_price' => 230000.00,
                'subtotal'         => 230000.00,
                'specifications'   => '{"length":80,"width":450,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK.80x450:1lbr( Kenzi kosmetik) UK.80x4:1lbr( Kiky kosmetik)  UK.80x2,5: 1lbr ( sarafina beauty)"}',
                'created_at'       => '2026-05-20 09:15:00',
                'updated_at'       => '2026-05-20 09:15:00',
            ],
            [
                'item_id'          => 31,
                'order_id'         => 58,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 47000000.00,
                'calculated_price' => 47000000.00,
                'subtotal'         => 47000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Repair Booth Wardah 2026"}',
                'created_at'       => '2026-01-23 03:00:00',
                'updated_at'       => '2026-01-23 03:00:00',
            ],
            [
                'item_id'          => 32,
                'order_id'         => 59,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 70000.00,
                'calculated_price' => 70000.00,
                'subtotal'         => 70000.00,
                'specifications'   => '{"length":120,"width":90,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 120x90 Private Les 2PCS"}',
                'created_at'       => '2026-01-20 03:30:00',
                'updated_at'       => '2026-01-20 03:30:00',
            ],
            [
                'item_id'          => 33,
                'order_id'         => 60,
                'product_id'       => 14,
                'product_name'     => 'BACKLITE',
                'quantity'         => 1.00,
                'price'            => 5250000.00,
                'calculated_price' => 5250000.00,
                'subtotal'         => 5250000.00,
                'specifications'   => '{"length":1,"width":1,"material":"BACKLITE","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Neon Box Toko Mas Karo-Karo"}',
                'created_at'       => '2026-01-26 03:00:00',
                'updated_at'       => '2026-01-26 03:00:00',
            ],
            [
                'item_id'          => 34,
                'order_id'         => 61,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 365500.00,
                'calculated_price' => 365500.00,
                'subtotal'         => 365500.00,
                'specifications'   => '{"length":1.25,"width":1.2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1m25x 1m20 SPANDUK JADWAL KHOTIB 1m25x3m50 (3pcs) (DABEL DENGAN BON 17)"}',
                'created_at'       => '2026-01-26 04:00:00',
                'updated_at'       => '2026-01-26 04:00:00',
            ],
            [
                'item_id'          => 35,
                'order_id'         => 62,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 125000.00,
                'calculated_price' => 125000.00,
                'subtotal'         => 125000.00,
                'specifications'   => '{"length":1,"width":5,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1x5 SELAMAT MENUNAIKAN IBADAH PUASA"}',
                'created_at'       => '2026-01-28 03:00:00',
                'updated_at'       => '2026-01-28 03:00:00',
            ],
            [
                'item_id'          => 36,
                'order_id'         => 63,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 145000.00,
                'calculated_price' => 145000.00,
                'subtotal'         => 145000.00,
                'specifications'   => '{"length":1,"width":4,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1x4 MAE.FLOO BOUQET AND GIFT"}',
                'created_at'       => '2026-01-28 04:00:00',
                'updated_at'       => '2026-01-28 04:00:00',
            ],
            [
                'item_id'          => 37,
                'order_id'         => 64,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 9500000.00,
                'calculated_price' => 9500000.00,
                'subtotal'         => 9500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi backdrop & gate KORMI SUMUT"}',
                'created_at'       => '2026-01-28 05:00:00',
                'updated_at'       => '2026-01-28 05:00:00',
            ],
            [
                'item_id'          => 38,
                'order_id'         => 65,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 30000.00,
                'calculated_price' => 30000.00,
                'subtotal'         => 30000.00,
                'specifications'   => '{"length":50,"width":2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK.50x2m OBAT HERBAL"}',
                'created_at'       => '2026-01-28 06:00:00',
                'updated_at'       => '2026-01-28 06:00:00',
            ],
            [
                'item_id'          => 39,
                'order_id'         => 66,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3000000.00,
                'calculated_price' => 3000000.00,
                'subtotal'         => 3000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth EMINA Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 07:00:00',
                'updated_at'       => '2026-01-20 07:00:00',
            ],
            [
                'item_id'          => 40,
                'order_id'         => 67,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 6000000.00,
                'calculated_price' => 6000000.00,
                'subtotal'         => 6000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth Makeover Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 08:00:00',
                'updated_at'       => '2026-01-20 08:00:00',
            ],
            [
                'item_id'          => 41,
                'order_id'         => 68,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3000000.00,
                'calculated_price' => 3000000.00,
                'subtotal'         => 3000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth OMG Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 09:00:00',
                'updated_at'       => '2026-01-20 09:00:00',
            ],
            [
                'item_id'          => 42,
                'order_id'         => 58,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 47000000.00,
                'calculated_price' => 47000000.00,
                'subtotal'         => 47000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Repair Booth Wardah 2026"}',
                'created_at'       => '2026-01-23 03:00:00',
                'updated_at'       => '2026-01-23 03:00:00',
            ],
            [
                'item_id'          => 43,
                'order_id'         => 59,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 70000.00,
                'calculated_price' => 70000.00,
                'subtotal'         => 70000.00,
                'specifications'   => '{"length":120,"width":90,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 120x90 Private Les 2PCS"}',
                'created_at'       => '2026-01-20 03:30:00',
                'updated_at'       => '2026-01-20 03:30:00',
            ],
            [
                'item_id'          => 44,
                'order_id'         => 60,
                'product_id'       => 14,
                'product_name'     => 'BACKLITE',
                'quantity'         => 1.00,
                'price'            => 5250000.00,
                'calculated_price' => 5250000.00,
                'subtotal'         => 5250000.00,
                'specifications'   => '{"length":1,"width":1,"material":"BACKLITE","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Neon Box Toko Mas Karo-Karo"}',
                'created_at'       => '2026-01-26 03:00:00',
                'updated_at'       => '2026-01-26 03:00:00',
            ],
            [
                'item_id'          => 45,
                'order_id'         => 61,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 365500.00,
                'calculated_price' => 365500.00,
                'subtotal'         => 365500.00,
                'specifications'   => '{"length":1.25,"width":1.2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1m25x 1m20 SPANDUK JADWAL KHOTIB 1m25x3m50 (3pcs) (DABEL DENGAN BON 17)"}',
                'created_at'       => '2026-01-26 04:00:00',
                'updated_at'       => '2026-01-26 04:00:00',
            ],
            [
                'item_id'          => 46,
                'order_id'         => 62,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 125000.00,
                'calculated_price' => 125000.00,
                'subtotal'         => 125000.00,
                'specifications'   => '{"length":1,"width":5,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1x5 SELAMAT MENUNAIKAN IBADAH PUASA"}',
                'created_at'       => '2026-01-28 03:00:00',
                'updated_at'       => '2026-01-28 03:00:00',
            ],
            [
                'item_id'          => 47,
                'order_id'         => 63,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 145000.00,
                'calculated_price' => 145000.00,
                'subtotal'         => 145000.00,
                'specifications'   => '{"length":1,"width":4,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk 1x4 MAE.FLOO BOUQET AND GIFT"}',
                'created_at'       => '2026-01-28 04:00:00',
                'updated_at'       => '2026-01-28 04:00:00',
            ],
            [
                'item_id'          => 48,
                'order_id'         => 64,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 9500000.00,
                'calculated_price' => 9500000.00,
                'subtotal'         => 9500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi backdrop & gate KORMI SUMUT"}',
                'created_at'       => '2026-01-28 05:00:00',
                'updated_at'       => '2026-01-28 05:00:00',
            ],
            [
                'item_id'          => 49,
                'order_id'         => 65,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 30000.00,
                'calculated_price' => 30000.00,
                'subtotal'         => 30000.00,
                'specifications'   => '{"length":50,"width":2,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk UK.50x2m OBAT HERBAL"}',
                'created_at'       => '2026-01-28 06:00:00',
                'updated_at'       => '2026-01-28 06:00:00',
            ],
            [
                'item_id'          => 50,
                'order_id'         => 66,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3000000.00,
                'calculated_price' => 3000000.00,
                'subtotal'         => 3000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth EMINA Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 07:00:00',
                'updated_at'       => '2026-01-20 07:00:00',
            ],
            [
                'item_id'          => 51,
                'order_id'         => 67,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 6000000.00,
                'calculated_price' => 6000000.00,
                'subtotal'         => 6000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth Makeover Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 08:00:00',
                'updated_at'       => '2026-01-20 08:00:00',
            ],
            [
                'item_id'          => 52,
                'order_id'         => 68,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3000000.00,
                'calculated_price' => 3000000.00,
                'subtotal'         => 3000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth OMG Medan Beauty Week TIARA CONVENTION"}',
                'created_at'       => '2026-01-20 09:00:00',
                'updated_at'       => '2026-01-20 09:00:00',
            ],
            [
                'item_id'          => 100,
                'order_id'         => 69,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 47000000.00,
                'calculated_price' => 47000000.00,
                'subtotal'         => 47000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Repair Booth Wardah Sun Plaza ( 1 UNIT )"}',
                'created_at'       => '2026-02-03 03:00:00',
                'updated_at'       => '2026-02-03 03:00:00',
            ],
            [
                'item_id'          => 101,
                'order_id'         => 70,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 8240000.00,
                'calculated_price' => 8240000.00,
                'subtotal'         => 8240000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi PNT Apotek Simpang Kampus"}',
                'created_at'       => '2026-02-05 03:00:00',
                'updated_at'       => '2026-02-05 03:00:00',
            ],
            [
                'item_id'          => 102,
                'order_id'         => 71,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 8500000.00,
                'calculated_price' => 8500000.00,
                'subtotal'         => 8500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Sewa backdrop+gate KORMI SUMUT"}',
                'created_at'       => '2026-02-05 03:00:00',
                'updated_at'       => '2026-02-05 03:00:00',
            ],
            [
                'item_id'          => 103,
                'order_id'         => 72,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 22000.00,
                'calculated_price' => 22000.00,
                'subtotal'         => 22000.00,
                'specifications'   => '{"length":2,"width":0.5,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"SPANDUK U. 2X0.5 (1lbr)"}',
                'created_at'       => '2026-02-05 03:00:00',
                'updated_at'       => '2026-02-05 03:00:00',
            ],
            [
                'item_id'          => 207,
                'order_id'         => 73,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 22000.00,
                'calculated_price' => 22000.00,
                'subtotal'         => 22000.00,
                'specifications'   => '{"length":1,"width":70,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"SPanduk 1x70 Ulang Tahun"}',
                'created_at'       => '2026-02-06 03:00:00',
                'updated_at'       => '2026-02-06 03:00:00',
            ],
            [
                'item_id'          => 208,
                'order_id'         => 74,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3000000.00,
                'calculated_price' => 3000000.00,
                'subtotal'         => 3000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth MakeOver Citraland"}',
                'created_at'       => '2026-02-09 03:00:00',
                'updated_at'       => '2026-02-09 03:00:00',
            ],
            [
                'item_id'          => 209,
                'order_id'         => 75,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 735000.00,
                'calculated_price' => 735000.00,
                'subtotal'         => 735000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk uk.1x1 IMLEK POCARI"}',
                'created_at'       => '2026-02-09 03:00:00',
                'updated_at'       => '2026-02-09 03:00:00',
            ],
            [
                'item_id'          => 210,
                'order_id'         => 76,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 412100.00,
                'calculated_price' => 412100.00,
                'subtotal'         => 412100.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk Ikmas Milad"}',
                'created_at'       => '2026-02-10 03:00:00',
                'updated_at'       => '2026-02-10 03:00:00',
            ],
            [
                'item_id'          => 211,
                'order_id'         => 77,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 1084602.00,
                'calculated_price' => 1084602.00,
                'subtotal'         => 1084602.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Spanduk Arya"}',
                'created_at'       => '2026-02-10 03:00:00',
                'updated_at'       => '2026-02-10 03:00:00',
            ],
            [
                'item_id'          => 212,
                'order_id'         => 81,
                'product_id'       => 17,
                'product_name'     => 'STICKER INDOOR',
                'quantity'         => 1.00,
                'price'            => 20000.00,
                'calculated_price' => 20000.00,
                'subtotal'         => 20000.00,
                'specifications'   => '{"length":1,"width":1,"material":"STICKER INDOOR","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Stiker 30cmx13 MAKEOVER"}',
                'created_at'       => '2026-02-11 03:00:00',
                'updated_at'       => '2026-02-11 03:00:00',
            ],
            [
                'item_id'          => 213,
                'order_id'         => 82,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 0.00,
                'calculated_price' => 0.00,
                'subtotal'         => 0.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Kalender Arya 25pcs"}',
                'created_at'       => '2026-02-11 03:00:00',
                'updated_at'       => '2026-02-11 03:00:00',
            ],
            [
                'item_id'          => 216,
                'order_id'         => 83,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 500000.00,
                'calculated_price' => 500000.00,
                'subtotal'         => 500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Produksi Spanduk Promo Maret"}',
                'created_at'       => '2026-03-01 03:00:00',
                'updated_at'       => '2026-03-01 03:00:00',
            ],
            [
                'item_id'          => 217,
                'order_id'         => 84,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 3500000.00,
                'calculated_price' => 3500000.00,
                'subtotal'         => 3500000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth EMINA Kim Kosmetik"}',
                'created_at'       => '2026-03-09 03:00:00',
                'updated_at'       => '2026-03-09 03:00:00',
            ],
            [
                'item_id'          => 218,
                'order_id'         => 85,
                'product_id'       => 8,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 2000000.00,
                'calculated_price' => 2000000.00,
                'subtotal'         => 2000000.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"Aktivasi Booth KAHF BARBER"}',
                'created_at'       => '2026-03-09 03:00:00',
                'updated_at'       => '2026-03-09 03:00:00',
            ],
            [
                'item_id'          => 219,
                'order_id'         => 116,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 21600.00,
                'calculated_price' => 21600.00,
                'subtotal'         => 21600.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"MMT 280GSM"}',
                'created_at'       => '2026-06-24 02:38:27',
                'updated_at'       => '2026-06-24 02:38:27',
            ],
            [
                'item_id'          => 220,
                'order_id'         => 117,
                'product_id'       => 11,
                'product_name'     => 'MMT 280GSM',
                'quantity'         => 1.00,
                'price'            => 21600.00,
                'calculated_price' => 21600.00,
                'subtotal'         => 21600.00,
                'specifications'   => '{"length":1,"width":1,"material":"MMT 280GSM","finishing":"","design_file":null}',
                'custom_details'   => '{"catatan":"MMT 280GSM"}',
                'created_at'       => '2026-06-24 02:51:17',
                'updated_at'       => '2026-06-24 02:51:17',
            ],
        ];

        // Pastikan tabel dikosongkan jika Kakak ingin melakukan refresh total, 
        // namun sebaiknya pakai insert saja agar tidak merusak data yang sudah berjalan.
        DB::table('order_items')->insert($orderItems);
    }
}