<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            [
                'order_id'          => 1,
                'order_number'      => 'ORD-20260109-0001',
                'customer_id'       => 10,
                'order_date'        => '2026-01-09 03:00:00',
                'total_amount'      => '13200000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-09 03:00:00',
                'updated_at'        => '2026-01-09 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Gadai Mas',
                'receiver_phone'    => '081111111111',
                'notes'             => 'Bon 1',
            ],
            [
                'order_id'          => 2,
                'order_number'      => 'ORD-20260109-0002',
                'customer_id'       => 11,
                'order_date'        => '2026-01-09 04:30:00',
                'total_amount'      => '120000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-09 04:30:00',
                'updated_at'        => '2026-01-09 04:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Isma',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 2',
            ],
            [
                'order_id'          => 3,
                'order_number'      => 'ORD-20260109-0003',
                'customer_id'       => 11,
                'order_date'        => '2026-01-09 06:15:00',
                'total_amount'      => '118750.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-09 06:15:00',
                'updated_at'        => '2026-01-09 06:15:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Pak Hasan',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 3',
            ],
            [
                'order_id'          => 4,
                'order_number'      => 'ORD-20260112-0004',
                'customer_id'       => 12,
                'order_date'        => '2026-01-12 02:00:00',
                'total_amount'      => '150000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-01-12 02:00:00',
                'updated_at'        => '2026-01-12 02:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Sarah',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 4',
            ],
            [
                'order_id'          => 5,
                'order_number'      => 'ORD-20260112-0006',
                'customer_id'       => 11,
                'order_date'        => '2026-01-12 07:00:00',
                'total_amount'      => '380000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-12 07:00:00',
                'updated_at'        => '2026-01-12 07:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 6',
            ],
            [
                'order_id'          => 6,
                'order_number'      => 'ORD-20260121-0012',
                'customer_id'       => 13,
                'order_date'        => '2026-01-21 03:20:00',
                'total_amount'      => '900000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-01-21 03:20:00',
                'updated_at'        => '2026-01-21 03:20:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Erwin',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 12',
            ],
            [
                'order_id'          => 7,
                'order_number'      => 'ORD-20260202-0027',
                'customer_id'       => 12,
                'order_date'        => '2026-02-02 04:00:00',
                'total_amount'      => '5000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-02 04:00:00',
                'updated_at'        => '2026-02-02 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Vina',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 27',
            ],
            [
                'order_id'          => 8,
                'order_number'      => 'ORD-20260210-0035',
                'customer_id'       => 14,
                'order_date'        => '2026-02-10 02:30:00',
                'total_amount'      => '412100.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-10 02:30:00',
                'updated_at'        => '2026-02-10 02:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Pak Hasan',
                'receiver_phone'    => '085555555555',
                'notes'             => 'Bon 35',
            ],
            [
                'order_id'          => 9,
                'order_number'      => 'ORD-20260218-0052',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:45:00',
                'total_amount'      => '8000000.00',
                'payment_proof_url' => null,
                'status'            => 'Verified',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:45:00',
                'updated_at'        => '2026-02-18 03:45:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Vina',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 52A (PO Terbit)',
            ],
            [
                'order_id'          => 10,
                'order_number'      => 'ORD-20260223-0065',
                'customer_id'       => 11,
                'order_date'        => '2026-02-23 08:00:00',
                'total_amount'      => '15000000.00',
                'payment_proof_url' => null,
                'status'            => 'Pending',
                'verified_by'       => null,
                'created_at'        => '2026-02-23 08:00:00',
                'updated_at'        => '2026-02-23 08:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Bpk Frans',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 65',
            ],
            [
                'order_id'          => 11,
                'order_number'      => 'ORD-20260331-108A',
                'customer_id'       => 13,
                'order_date'        => '2026-03-31 02:10:00',
                'total_amount'      => '2415000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-03-31 02:10:00',
                'updated_at'        => '2026-03-31 02:10:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Ammar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 108A',
            ],
            [
                'order_id'          => 12,
                'order_number'      => 'ORD-20260331-108B',
                'customer_id'       => 13,
                'order_date'        => '2026-03-31 03:15:00',
                'total_amount'      => '1680000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-03-31 03:15:00',
                'updated_at'        => '2026-03-31 03:15:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Ammar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 108B',
            ],
            [
                'order_id'          => 13,
                'order_number'      => 'ORD-20260331-0112',
                'customer_id'       => 13,
                'order_date'        => '2026-03-31 04:30:00',
                'total_amount'      => '600000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-03-31 04:30:00',
                'updated_at'        => '2026-03-31 04:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Ammar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 112',
            ],
            [
                'order_id'          => 14,
                'order_number'      => 'ORD-20260505-148A',
                'customer_id'       => 13,
                'order_date'        => '2026-05-05 06:00:00',
                'total_amount'      => '3500000.00',
                'payment_proof_url' => null,
                'status'            => 'Verified',
                'verified_by'       => 2,
                'created_at'        => '2026-05-05 06:00:00',
                'updated_at'        => '2026-05-05 06:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Amar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 148A (PO Terbit)',
            ],
            [
                'order_id'          => 15,
                'order_number'      => 'ORD-20260505-148B',
                'customer_id'       => 13,
                'order_date'        => '2026-05-05 06:10:00',
                'total_amount'      => '3500000.00',
                'payment_proof_url' => null,
                'status'            => 'Verified',
                'verified_by'       => 2,
                'created_at'        => '2026-05-05 06:10:00',
                'updated_at'        => '2026-05-05 06:10:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Amar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 148B (PO Terbit)',
            ],
            [
                'order_id'          => 16,
                'order_number'      => 'ORD-20260505-148C',
                'customer_id'       => 13,
                'order_date'        => '2026-05-05 06:20:00',
                'total_amount'      => '3500000.00',
                'payment_proof_url' => null,
                'status'            => 'Verified',
                'verified_by'       => 2,
                'created_at'        => '2026-05-05 06:20:00',
                'updated_at'        => '2026-05-05 06:20:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Amar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 148C',
            ],
            [
                'order_id'          => 17,
                'order_number'      => 'ORD-20260505-148D',
                'customer_id'       => 13,
                'order_date'        => '2026-05-05 06:30:00',
                'total_amount'      => '3500000.00',
                'payment_proof_url' => null,
                'status'            => 'Verified',
                'verified_by'       => 2,
                'created_at'        => '2026-05-05 06:30:00',
                'updated_at'        => '2026-05-05 06:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Amar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 148D',
            ],
            [
                'order_id'          => 18,
                'order_number'      => 'ORD-20260506-0149',
                'customer_id'       => 13,
                'order_date'        => '2026-05-06 03:00:00',
                'total_amount'      => '500000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-06 03:00:00',
                'updated_at'        => '2026-05-06 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Amar',
                'receiver_phone'    => '084444444444',
                'notes'             => 'Bon 149',
            ],
            [
                'order_id'          => 19,
                'order_number'      => 'ORD-20260507-0150',
                'customer_id'       => 15,
                'order_date'        => '2026-05-07 02:00:00',
                'total_amount'      => '3774720.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-07 02:00:00',
                'updated_at'        => '2026-05-07 02:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Indofood Rep',
                'receiver_phone'    => '086666666666',
                'notes'             => 'Bon 150',
            ],
            [
                'order_id'          => 20,
                'order_number'      => 'ORD-20260507-0151',
                'customer_id'       => 11,
                'order_date'        => '2026-05-07 04:30:00',
                'total_amount'      => '70000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-05-07 04:30:00',
                'updated_at'        => '2026-05-07 04:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 151',
            ],
            [
                'order_id'          => 21,
                'order_number'      => 'ORD-20260508-0152',
                'customer_id'       => 12,
                'order_date'        => '2026-05-08 07:00:00',
                'total_amount'      => '850000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-08 07:00:00',
                'updated_at'        => '2026-05-08 07:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 152',
            ],
            [
                'order_id'          => 22,
                'order_number'      => 'ORD-20260511-0153',
                'customer_id'       => 15,
                'order_date'        => '2026-05-11 03:15:00',
                'total_amount'      => '23454750.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-11 03:15:00',
                'updated_at'        => '2026-05-11 03:15:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Indofood Rep',
                'receiver_phone'    => '086666666666',
                'notes'             => 'Bon 153',
            ],
            [
                'order_id'          => 23,
                'order_number'      => 'ORD-20260519-0154',
                'customer_id'       => 11,
                'order_date'        => '2026-05-19 02:30:00',
                'total_amount'      => '3500000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-05-19 02:30:00',
                'updated_at'        => '2026-05-19 02:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 154',
            ],
            [
                'order_id'          => 24,
                'order_number'      => 'ORD-20260513-0155',
                'customer_id'       => 12,
                'order_date'        => '2026-05-13 06:45:00',
                'total_amount'      => '500000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-13 06:45:00',
                'updated_at'        => '2026-05-13 06:45:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 155',
            ],
            [
                'order_id'          => 25,
                'order_number'      => 'ORD-20260513-0158',
                'customer_id'       => 12,
                'order_date'        => '2026-05-13 08:00:00',
                'total_amount'      => '350000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-05-13 08:00:00',
                'updated_at'        => '2026-05-13 08:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 158',
            ],
            [
                'order_id'          => 26,
                'order_number'      => 'ORD-20260519-0159',
                'customer_id'       => 11,
                'order_date'        => '2026-05-19 04:20:00',
                'total_amount'      => '4000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-19 04:20:00',
                'updated_at'        => '2026-05-19 04:20:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum',
                'receiver_phone'    => '082222222222',
                'notes'             => 'Bon 159',
            ],
            [
                'order_id'          => 27,
                'order_number'      => 'ORD-20260510-0160',
                'customer_id'       => 12,
                'order_date'        => '2026-05-10 02:00:00',
                'total_amount'      => '500000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-10 02:00:00',
                'updated_at'        => '2026-05-10 02:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 160',
            ],
            [
                'order_id'          => 28,
                'order_number'      => 'ORD-20260520-0162',
                'customer_id'       => 16,
                'order_date'        => '2026-05-20 03:30:00',
                'total_amount'      => '35000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-20 03:30:00',
                'updated_at'        => '2026-05-20 03:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Assi Rep',
                'receiver_phone'    => '087777777777',
                'notes'             => 'Bon 162',
            ],
            [
                'order_id'          => 29,
                'order_number'      => 'ORD-20260520-0164',
                'customer_id'       => 17,
                'order_date'        => '2026-05-20 07:00:00',
                'total_amount'      => '22400.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-20 07:00:00',
                'updated_at'        => '2026-05-20 07:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Adv Rep',
                'receiver_phone'    => '088888888888',
                'notes'             => 'Bon 164',
            ],
            [
                'order_id'          => 30,
                'order_number'      => 'ORD-20260520-0165',
                'customer_id'       => 12,
                'order_date'        => '2026-05-20 09:15:00',
                'total_amount'      => '230000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-05-20 09:15:00',
                'updated_at'        => '2026-05-20 09:15:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '083333333333',
                'notes'             => 'Bon 165',
            ],
            [
                'order_id'          => 46,
                'order_number'      => 'ORD-20260112-0005',
                'customer_id'       => 20,
                'order_date'        => '2026-01-12 03:00:00',
                'total_amount'      => '150000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-12 03:00:00',
                'updated_at'        => '2026-01-12 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Kormi Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 5',
            ],
            [
                'order_id'          => 47,
                'order_number'      => 'ORD-20260115-0007',
                'customer_id'       => 11,
                'order_date'        => '2026-01-15 03:00:00',
                'total_amount'      => '118750.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-15 03:00:00',
                'updated_at'        => '2026-01-15 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 7',
            ],
            [
                'order_id'          => 48,
                'order_number'      => 'ORD-20260115-0008',
                'customer_id'       => 11,
                'order_date'        => '2026-01-15 04:00:00',
                'total_amount'      => '160000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-15 04:00:00',
                'updated_at'        => '2026-01-15 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 8',
            ],
            [
                'order_id'          => 49,
                'order_number'      => 'ORD-20260115-0009',
                'customer_id'       => 13,
                'order_date'        => '2026-01-15 05:00:00',
                'total_amount'      => '900000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-15 05:00:00',
                'updated_at'        => '2026-01-15 05:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Djarum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 9',
            ],
            [
                'order_id'          => 50,
                'order_number'      => 'ORD-20260115-0010',
                'customer_id'       => 20,
                'order_date'        => '2026-01-15 06:00:00',
                'total_amount'      => '50000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-15 06:00:00',
                'updated_at'        => '2026-01-15 06:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Kormi Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 10',
            ],
            [
                'order_id'          => 51,
                'order_number'      => 'ORD-20260119-0011',
                'customer_id'       => 11,
                'order_date'        => '2026-01-19 03:00:00',
                'total_amount'      => '400000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-19 03:00:00',
                'updated_at'        => '2026-01-19 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 11',
            ],
            [
                'order_id'          => 52,
                'order_number'      => 'ORD-20260119-0013',
                'customer_id'       => 11,
                'order_date'        => '2026-01-19 04:00:00',
                'total_amount'      => '600000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-01-19 04:00:00',
                'updated_at'        => '2026-01-19 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 13',
            ],
            [
                'order_id'          => 53,
                'order_number'      => 'ORD-20260120-0014',
                'customer_id'       => 12,
                'order_date'        => '2026-01-20 03:00:00',
                'total_amount'      => '30000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 03:00:00',
                'updated_at'        => '2026-01-20 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 14',
            ],
            [
                'order_id'          => 54,
                'order_number'      => 'ORD-20260120-014B',
                'customer_id'       => 21,
                'order_date'        => '2026-01-20 04:00:00',
                'total_amount'      => '3000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 04:00:00',
                'updated_at'        => '2026-01-20 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Varcos Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 14B',
            ],
            [
                'order_id'          => 55,
                'order_number'      => 'ORD-20260120-0015',
                'customer_id'       => 11,
                'order_date'        => '2026-01-20 05:00:00',
                'total_amount'      => '120000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 05:00:00',
                'updated_at'        => '2026-01-20 05:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 15',
            ],
            [
                'order_id'          => 56,
                'order_number'      => 'ORD-20260121-0016',
                'customer_id'       => 13,
                'order_date'        => '2026-01-21 03:00:00',
                'total_amount'      => '525000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-21 03:00:00',
                'updated_at'        => '2026-01-21 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Djarum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 16',
            ],
            [
                'order_id'          => 57,
                'order_number'      => 'ORD-20260122-0017',
                'customer_id'       => 11,
                'order_date'        => '2026-01-22 03:00:00',
                'total_amount'      => '485000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-22 03:00:00',
                'updated_at'        => '2026-01-22 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 17',
            ],
            [
                'order_id'          => 58,
                'order_number'      => 'ORD-20260123-0018',
                'customer_id'       => 12,
                'order_date'        => '2026-01-23 03:00:00',
                'total_amount'      => '47000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-23 03:00:00',
                'updated_at'        => '2026-01-23 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 18',
            ],
            [
                'order_id'          => 59,
                'order_number'      => 'ORD-20260120-0019',
                'customer_id'       => 11,
                'order_date'        => '2026-01-20 03:30:00',
                'total_amount'      => '70000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 03:30:00',
                'updated_at'        => '2026-01-20 03:30:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 19',
            ],
            [
                'order_id'          => 60,
                'order_number'      => 'ORD-20260126-0020',
                'customer_id'       => 11,
                'order_date'        => '2026-01-26 03:00:00',
                'total_amount'      => '5250000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-26 03:00:00',
                'updated_at'        => '2026-01-26 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 20',
            ],
            [
                'order_id'          => 61,
                'order_number'      => 'ORD-20260126-0021',
                'customer_id'       => 11,
                'order_date'        => '2026-01-26 04:00:00',
                'total_amount'      => '365500.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-01-26 04:00:00',
                'updated_at'        => '2026-01-26 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 21',
            ],
            [
                'order_id'          => 62,
                'order_number'      => 'ORD-20260128-0022',
                'customer_id'       => 11,
                'order_date'        => '2026-01-28 03:00:00',
                'total_amount'      => '125000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-28 03:00:00',
                'updated_at'        => '2026-01-28 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 22',
            ],
            [
                'order_id'          => 63,
                'order_number'      => 'ORD-20260128-0023',
                'customer_id'       => 11,
                'order_date'        => '2026-01-28 04:00:00',
                'total_amount'      => '145000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-28 04:00:00',
                'updated_at'        => '2026-01-28 04:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 23',
            ],
            [
                'order_id'          => 64,
                'order_number'      => 'ORD-20260128-0024',
                'customer_id'       => 20,
                'order_date'        => '2026-01-28 05:00:00',
                'total_amount'      => '9500000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-28 05:00:00',
                'updated_at'        => '2026-01-28 05:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Kormi Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 24',
            ],
            [
                'order_id'          => 65,
                'order_number'      => 'ORD-20260128-0025',
                'customer_id'       => 11,
                'order_date'        => '2026-01-28 06:00:00',
                'total_amount'      => '30000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-28 06:00:00',
                'updated_at'        => '2026-01-28 06:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 25',
            ],
            [
                'order_id'          => 66,
                'order_number'      => 'ORD-20260120-026A',
                'customer_id'       => 12,
                'order_date'        => '2026-01-20 07:00:00',
                'total_amount'      => '3000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 07:00:00',
                'updated_at'        => '2026-01-20 07:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 26A',
            ],
            [
                'order_id'          => 67,
                'order_number'      => 'ORD-20260120-026B',
                'customer_id'       => 12,
                'order_date'        => '2026-01-20 08:00:00',
                'total_amount'      => '6000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 08:00:00',
                'updated_at'        => '2026-01-20 08:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 26B',
            ],
            [
                'order_id'          => 68,
                'order_number'      => 'ORD-20260120-026C',
                'customer_id'       => 12,
                'order_date'        => '2026-01-20 09:00:00',
                'total_amount'      => '3000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-01-20 09:00:00',
                'updated_at'        => '2026-01-20 09:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 26C',
            ],
            [
                'order_id'          => 69,
                'order_number'      => 'ORD-20260203-028',
                'customer_id'       => 12,
                'order_date'        => '2026-02-03 03:00:00',
                'total_amount'      => '47000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-03 03:00:00',
                'updated_at'        => '2026-02-03 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 28',
            ],
            [
                'order_id'          => 70,
                'order_number'      => 'ORD-20260205-029',
                'customer_id'       => 11,
                'order_date'        => '2026-02-05 03:00:00',
                'total_amount'      => '8240000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-05 03:00:00',
                'updated_at'        => '2026-02-05 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 29',
            ],
            [
                'order_id'          => 71,
                'order_number'      => 'ORD-20260205-030',
                'customer_id'       => 20,
                'order_date'        => '2026-02-05 03:00:00',
                'total_amount'      => '8500000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-05 03:00:00',
                'updated_at'        => '2026-02-05 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Kormi Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 30',
            ],
            [
                'order_id'          => 72,
                'order_number'      => 'ORD-20260205-031',
                'customer_id'       => 11,
                'order_date'        => '2026-02-05 03:00:00',
                'total_amount'      => '22000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-05 03:00:00',
                'updated_at'        => '2026-02-05 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 31',
            ],
            [
                'order_id'          => 73,
                'order_number'      => 'ORD-20260206-032',
                'customer_id'       => 11,
                'order_date'        => '2026-02-06 03:00:00',
                'total_amount'      => '22000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-06 03:00:00',
                'updated_at'        => '2026-02-06 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 32',
            ],
            [
                'order_id'          => 74,
                'order_number'      => 'ORD-20260209-033',
                'customer_id'       => 12,
                'order_date'        => '2026-02-09 03:00:00',
                'total_amount'      => '3000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-09 03:00:00',
                'updated_at'        => '2026-02-09 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 33',
            ],
            [
                'order_id'          => 75,
                'order_number'      => 'ORD-20260209-034',
                'customer_id'       => 22,
                'order_date'        => '2026-02-09 03:00:00',
                'total_amount'      => '735000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-09 03:00:00',
                'updated_at'        => '2026-02-09 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Pocari Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 34',
            ],
            [
                'order_id'          => 76,
                'order_number'      => 'ORD-20260210-036',
                'customer_id'       => 23,
                'order_date'        => '2026-02-10 03:00:00',
                'total_amount'      => '1084602.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-10 03:00:00',
                'updated_at'        => '2026-02-10 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Arya Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 36',
            ],
            [
                'order_id'          => 77,
                'order_number'      => 'ORD-20260210-037',
                'customer_id'       => 23,
                'order_date'        => '2026-02-10 03:00:00',
                'total_amount'      => '97000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-10 03:00:00',
                'updated_at'        => '2026-02-10 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Arya Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 37',
            ],
            [
                'order_id'          => 78,
                'order_number'      => 'ORD-20260210-038',
                'customer_id'       => 11,
                'order_date'        => '2026-02-10 03:00:00',
                'total_amount'      => '100000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-10 03:00:00',
                'updated_at'        => '2026-02-10 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 38',
            ],
            [
                'order_id'          => 81,
                'order_number'      => 'ORD-20260211-041',
                'customer_id'       => 23,
                'order_date'        => '2026-02-11 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-11 03:00:00',
                'updated_at'        => '2026-02-11 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Arya Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 41',
            ],
            [
                'order_id'          => 82,
                'order_number'      => 'ORD-20260211-042',
                'customer_id'       => 20,
                'order_date'        => '2026-02-11 03:00:00',
                'total_amount'      => '500000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-11 03:00:00',
                'updated_at'        => '2026-02-11 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Kormi Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 42',
            ],
            [
                'order_id'          => 83,
                'order_number'      => 'ORD-20260211-043',
                'customer_id'       => 11,
                'order_date'        => '2026-02-11 03:00:00',
                'total_amount'      => '30000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-11 03:00:00',
                'updated_at'        => '2026-02-11 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 43',
            ],
            [
                'order_id'          => 84,
                'order_number'      => 'ORD-20260211-044',
                'customer_id'       => 24,
                'order_date'        => '2026-02-11 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-11 03:00:00',
                'updated_at'        => '2026-02-11 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Keind Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 44',
            ],
            [
                'order_id'          => 85,
                'order_number'      => 'ORD-20260211-045',
                'customer_id'       => 25,
                'order_date'        => '2026-02-11 03:00:00',
                'total_amount'      => '27280.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-11 03:00:00',
                'updated_at'        => '2026-02-11 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Jhsf Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 45',
            ],
            [
                'order_id'          => 86,
                'order_number'      => 'ORD-20260212-046',
                'customer_id'       => 12,
                'order_date'        => '2026-02-12 03:00:00',
                'total_amount'      => '6500000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-12 03:00:00',
                'updated_at'        => '2026-02-12 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 46',
            ],
            [
                'order_id'          => 87,
                'order_number'      => 'ORD-20260218-047',
                'customer_id'       => 26,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '3000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Suntone Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 47',
            ],
            [
                'order_id'          => 89,
                'order_number'      => 'ORD-20260218-049',
                'customer_id'       => 13,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '1800000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Djarum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 49',
            ],
            [
                'order_id'          => 90,
                'order_number'      => 'ORD-20260218-050',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 50',
            ],
            [
                'order_id'          => 91,
                'order_number'      => 'ORD-20260218-051A',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '8000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 51A',
            ],
            [
                'order_id'          => 92,
                'order_number'      => 'ORD-20260218-052B',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '6000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 52B',
            ],
            [
                'order_id'          => 93,
                'order_number'      => 'ORD-20260218-053',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 53',
            ],
            [
                'order_id'          => 94,
                'order_number'      => 'ORD-20260218-054A',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '4000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 54A',
            ],
            [
                'order_id'          => 95,
                'order_number'      => 'ORD-20260218-054B',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 54B',
            ],
            [
                'order_id'          => 96,
                'order_number'      => 'ORD-20260218-055A',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 55A',
            ],
            [
                'order_id'          => 97,
                'order_number'      => 'ORD-20260218-055B',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 55B',
            ],
            [
                'order_id'          => 98,
                'order_number'      => 'ORD-20260218-056',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 56',
            ],
            [
                'order_id'          => 99,
                'order_number'      => 'ORD-20260218-057',
                'customer_id'       => 12,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '4000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 57',
            ],
            [
                'order_id'          => 100,
                'order_number'      => 'ORD-20260213-058',
                'customer_id'       => 27,
                'order_date'        => '2026-02-13 03:00:00',
                'total_amount'      => '450000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-13 03:00:00',
                'updated_at'        => '2026-02-13 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Als Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 58',
            ],
            [
                'order_id'          => 101,
                'order_number'      => 'ORD-20260218-059',
                'customer_id'       => 28,
                'order_date'        => '2026-02-18 03:00:00',
                'total_amount'      => '1350000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-18 03:00:00',
                'updated_at'        => '2026-02-18 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Sulthon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 59',
            ],
            [
                'order_id'          => 102,
                'order_number'      => 'ORD-20260220-061',
                'customer_id'       => 12,
                'order_date'        => '2026-02-20 03:00:00',
                'total_amount'      => '1450000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-20 03:00:00',
                'updated_at'        => '2026-02-20 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 61',
            ],
            [
                'order_id'          => 103,
                'order_number'      => 'ORD-20260220-062',
                'customer_id'       => 26,
                'order_date'        => '2026-02-20 03:00:00',
                'total_amount'      => '1000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-20 03:00:00',
                'updated_at'        => '2026-02-20 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Suntone Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 62',
            ],
            [
                'order_id'          => 104,
                'order_number'      => 'ORD-20260220-063',
                'customer_id'       => 12,
                'order_date'        => '2026-02-20 03:00:00',
                'total_amount'      => '6000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-20 03:00:00',
                'updated_at'        => '2026-02-20 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 63',
            ],
            [
                'order_id'          => 105,
                'order_number'      => 'ORD-20260223-064',
                'customer_id'       => 12,
                'order_date'        => '2026-02-23 03:00:00',
                'total_amount'      => '13000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-23 03:00:00',
                'updated_at'        => '2026-02-23 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 64',
            ],
            [
                'order_id'          => 106,
                'order_number'      => 'ORD-20260223-066',
                'customer_id'       => 12,
                'order_date'        => '2026-02-23 03:00:00',
                'total_amount'      => '4000000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-23 03:00:00',
                'updated_at'        => '2026-02-23 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 66',
            ],
            [
                'order_id'          => 107,
                'order_number'      => 'ORD-20260223-067',
                'customer_id'       => 11,
                'order_date'        => '2026-02-23 03:00:00',
                'total_amount'      => '60000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-23 03:00:00',
                'updated_at'        => '2026-02-23 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Umum Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 67',
            ],
            [
                'order_id'          => 108,
                'order_number'      => 'ORD-20260224-068',
                'customer_id'       => 12,
                'order_date'        => '2026-02-24 03:00:00',
                'total_amount'      => '0.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-24 03:00:00',
                'updated_at'        => '2026-02-24 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 68',
            ],
            [
                'order_id'          => 109,
                'order_number'      => 'ORD-20260225-069',
                'customer_id'       => 12,
                'order_date'        => '2026-02-25 03:00:00',
                'total_amount'      => '2800000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-25 03:00:00',
                'updated_at'        => '2026-02-25 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 69',
            ],
            [
                'order_id'          => 110,
                'order_number'      => 'ORD-20260225-070',
                'customer_id'       => 12,
                'order_date'        => '2026-02-25 03:00:00',
                'total_amount'      => '30000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-25 03:00:00',
                'updated_at'        => '2026-02-25 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 70',
            ],
            [
                'order_id'          => 111,
                'order_number'      => 'ORD-20260226-071',
                'customer_id'       => 12,
                'order_date'        => '2026-02-26 03:00:00',
                'total_amount'      => '37000000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-26 03:00:00',
                'updated_at'        => '2026-02-26 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 71',
            ],
            [
                'order_id'          => 112,
                'order_number'      => 'ORD-20260226-072',
                'customer_id'       => 12,
                'order_date'        => '2026-02-26 03:00:00',
                'total_amount'      => '700000.00',
                'payment_proof_url' => null,
                'status'            => 'Completed',
                'verified_by'       => 2,
                'created_at'        => '2026-02-26 03:00:00',
                'updated_at'        => '2026-02-26 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 72',
            ],
            [
                'order_id'          => 114,
                'order_number'      => 'ORD-20260227-074',
                'customer_id'       => 12,
                'order_date'        => '2026-02-27 03:00:00',
                'total_amount'      => '1450000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-27 03:00:00',
                'updated_at'        => '2026-02-27 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 74',
            ],
            [
                'order_id'          => 115,
                'order_number'      => 'ORD-20260213-098',
                'customer_id'       => 12,
                'order_date'        => '2026-02-13 03:00:00',
                'total_amount'      => '210000.00',
                'payment_proof_url' => null,
                'status'            => 'Processing',
                'verified_by'       => 2,
                'created_at'        => '2026-02-13 03:00:00',
                'updated_at'        => '2026-02-13 03:00:00',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diambil di Toko',
                'receiver_name'     => 'Paragon Rep',
                'receiver_phone'    => '089999999999',
                'notes'             => 'Bon 98',
            ],
            [
                'order_id'          => 116,
                'order_number'      => 'ORD-202606240938276148',
                'customer_id'       => 9,
                'order_date'        => '2026-06-24 02:38:27',
                'total_amount'      => '21600.00',
                'payment_proof_url' => 'payment_proofs/payment-9-1782293929.jpg',
                'status'            => 'Awaiting Approval',
                'verified_by'       => null,
                'created_at'        => '2026-06-24 02:38:27',
                'updated_at'        => '2026-06-24 02:38:49',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diskusi via WhatsApp / Ambil di Toko',
                'receiver_name'     => 'Mariska Siagian',
                'receiver_phone'    => '876546576879',
                'notes'             => null,
            ],
            [
                'order_id'          => 117,
                'order_number'      => 'ORD-202606240951172040',
                'customer_id'       => 9,
                'order_date'        => '2026-06-24 02:51:17',
                'total_amount'      => '21600.00',
                'payment_proof_url' => 'payment_proofs/payment-9-1782294685.png',
                'status'            => 'Awaiting Approval',
                'verified_by'       => null,
                'created_at'        => '2026-06-24 02:51:17',
                'updated_at'        => '2026-06-24 02:51:25',
                'shipping_method'   => 'pickup',
                'shipping_address'  => 'Diskusi via WhatsApp / Ambil di Toko',
                'receiver_name'     => 'Mariska Siagian',
                'receiver_phone'    => '876546576879',
                'notes'             => null,
            ],
        ];

        DB::table('orders')->insert($orders);
    }
}
